### ISSUE TITLE
Can't start server: NumPy version different than Previously used

### ISSUE THREAD

**Issue by srwaggon** [inpho/inphosemantics-frontend#32]
When attempting to start up the tinytornado.py server, a flood of errors related to numpy are presented. Since the inphosemantics egg has not been updated for the inpho user on inphodata, it seems to me that  the version of NumPy has changed (regressed?) on the development box.

/usr/local/lib/python2.6/dist-packages/scipy/**init**.py:97: UserWarning: Numpy 
1.5.0 or above is recommended for this version of scipy (detected version 1.4.1)
  UserWarning)
RuntimeError: module compiled against API version 6 but this version of numpy is
 4
RuntimeError: module compiled against API version 6 but this version of numpy is
 4
RuntimeError: module compiled against API version 6 but this version of numpy is
 4
Traceback (most recent call last):
  File "./tinytornado.py", line 5, in <module>
    from inphosemantics import inpho # Used for semantic processing.
  File "/home/inpho/.local/lib/python2.6/site-packages/inphosemantics-0.1-py2.6.
egg/inphosemantics/inpho/**init**.py", line 19, in <module>
    from inphosemantics.model.tf import TfModel
  File "/home/inpho/.local/lib/python2.6/site-packages/inphosemantics-0.1-py2.6.
egg/inphosemantics/model/**init**.py", line 5, in <module>
    from scipy.sparse import issparse
  File "/usr/local/lib/python2.6/dist-packages/scipy/sparse/**init**.py", line 1
75, in <module>
    from csr import *
  File "/usr/local/lib/python2.6/dist-packages/scipy/sparse/csr.py", line 12, in
 <module>
    from sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
  File "/usr/local/lib/python2.6/dist-packages/scipy/sparse/sparsetools/**init**
.py", line 4, in <module>
    from csr import *
  File "/usr/local/lib/python2.6/dist-packages/scipy/sparse/sparsetools/csr.py",
 line 25, in <module>
    _csr = swig_import_helper()
  File "/usr/local/lib/python2.6/dist-packages/scipy/sparse/sparsetools/csr.py",
 line 21, in swig_import_helper
    _mod = imp.load_module('_csr', fp, pathname, description)
ImportError: numpy.core.multiarray failed to import

**Comment by rrose1** [comment]
Please try it again. I've removed the system-wide local installation of
these numpy/scipy. I'd forgotten to remove these last spring after some
compilation troubles.

**Comment by srwaggon** [comment]
Removing the system-wide installation fixed the issue.
